project:
  type: website
  output-dir: docs

execute:
    freeze: auto

website:
  title: "RFM 2026"
  navbar:
    background: primary
    right:
      - href: program.qmd
        text: Program
      - href: venue.qmd
        text: Venue
      - href: travelinfo.qmd
        text: Travel Information
  page-footer: ""

format:
  html:
    theme: minty
    css: styles.css
    toc: true
