---
pagetitle: "Travel  Information"
toc: false
---

## Hotel

I recommend the [Ibis hotel "Rotterdam City Centre"](https://all.accor.com/hotel/8188/index.en.shtml), which is located centrally next to [Market hall](https://www.rotterdam.info/en/visit/finder-locations/markthal) and the famous [Cube Houses](https://www.rotterdam.info/en/visit/finder-locations/kubuswoningen-kijk-kubus-museumwoning) houses. The hotel is also within walking distance of many restaurants and bars in the city center.

If you want to stay close to the campus, you might consider [Novotel Rotterdam Brainpark](https://all.accor.com/hotel//1134/index.en.shtml).


## Travel Information

### To Rotterdam

Rotterdam is well-connected by train to major cities in the Netherlands and neighboring countries as well as to the airport **Amsterdam Schiphol**. The main train station is **Rotterdam Central Station** located in the city center.  Trains run frequently, and you can check the schedule on the [NS website](https://www.ns.nl/en).

**by Car**: Parking in Rotterdam can be expensive and limited, especially in the city center. If you are driving, consider parking at Park & Ride (P+R) facility and take a tram/metro to the city center.


### Within Rotterdam

From Rotterdam city center to the campus, you can take either tram **line 11** (direction **De Esch**) to the station **Woudestein** or tram **line 7** (direction **Woudestein**) to station **Erasmus Universiteit**. Travel information can be found on the [RET website](https://www.ret.nl/en).

**Note**: In the Netherlands, there are no ticket machines at the tram stops or in buses but you can easily pay with a contactless debit or credit card when boarding the tram (called [OVPay](https://www.holland.com/global/tourism/getting-around/information/getting-around-in-the-netherlands/pay-in-public-transport)). Just tap your card on the card reader when you get on the bus/tram/metro.  Importantly, when you exit you have to tap your card again (check out) to calculate the fare based on the distance travelled. You can also buy tickets at some few stations, but this is more expensive and not recommended


